[package]
name = "repliq-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bench]]
name = "enqueue_benchmark"
harness = false

[dev-dependencies]
criterion = "0.4" # Or your preferred benchmarking crate
